{% set name = "gmpyinfr_log" %}
{% set version = "0.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gmpyinfr_log-{{ version }}.tar.gz
  sha256: 5aa3a8ce99e21db6479372883321724af47020328513cf2919bba8cdf9d0e77d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - gmpyinfr_log
    - gmpyinfr_log.dsgpttn
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/gmpyinfr-log/
  summary: Infraestrutura de log python de uma equipe de Ciencia de Dados
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anewmanvs
